require 'stringio'
require 'test/unit'
require File.dirname(__FILE__) + '/../lib/querybuilder'
require File.dirname(__FILE__) + '/mock/dummy_processor'
require File.dirname(__FILE__) + '/mock/user_processor'
require 'rubygems'
require 'yamltest'
