require 'stringio'
require 'test/unit'
require File.dirname(__FILE__) + '/../lib/QueryBuilder'
require File.dirname(__FILE__) + '/../lib/new_query_builder'
require File.dirname(__FILE__) + '/../lib/parser'
require File.dirname(__FILE__) + '/mock/dummy_query'
require File.dirname(__FILE__) + '/mock/dummy_processor'
require File.dirname(__FILE__) + '/mock/user_processor'
require File.dirname(__FILE__) + '/mock/user_query'
require 'rubygems'
require 'yamltest'
